version: '3.8'
services:
  cdk:
    build:
      context: .
      dockerfile: Dockerfile
    image: cdk
    container_name: cdk
    tty: true
    volumes:
      - /app/node_modules
      - .:/app:cached
      - ~/.aws:/home/.aws:cached
  # download_pdf_lambda:
  #   build:
  #     context: .
  #     dockerfile: ./services/download_pdf/lambda/Dockerfile
  #   volumes:
  #     # - ./services/download_pdf/lambda/dist:/usr/app/dist
  #     - ./services/download_pdf/lambda/dist:/app/services/download_pdf/lambda/dist
  #   ports:
  #     - 9000:8080
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #     - develop.host.docker.internal:host-gateway

  #   environment:
  #     - "LOCAL_TEST=${LOCAL_TEST}"
  #     - "AWS_REGION=ap-northeast-1"
  #     - "S3_ACTIVE_STORAGE_BUCKET=test-bucket"
  #   networks:
  #     - cdk_network
  # billing_notification_lambda:
  #   build:
  #     context: .
  #     dockerfile: ./services/billing_notification/lambda/Dockerfile
  #   volumes:
  #     - ./services/billing_notification/lambda/dist:/usr/app/dist
  #   ports:
  #     - 9001:8080
networks:
 cdk_network:
    external: true